/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MockWBTC__factory } from "./MockWBTC__factory";
export { MockWETH__factory } from "./MockWETH__factory";
